### PR TITLE
Create UIColor+TDAdditions.m

### PR DESCRIPTION
**Pull request by Havock94**
Added control to luminance as well, otherwise colors in grey scale would all be NOT DISTINCT

### CODE REVIEW

**Comment by timominous** [comment]
@Havock94 looks good

**Comment by Havock94** [comment]
@timominous is it possible to do that through the GitHub website? I don't find any way to do that

**Comment by timominous** [comment]
You'd have to modify it locally and push it again as a new commit on a new branch

**Comment by Havock94** [comment]
@timominous I added a clearer explanation of the edits, I hope this one will be more explicative.

**Comment by timominous** [comment]
@Havock94 merged

**Pull request merged**
